# Generated by Django 3.2.7 on 2021-10-11 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0007_alter_apartment_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_count',
        ),
        migrations.AddField(
            model_name='contact',
            name='seller',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
