# Generated by Django 3.2.7 on 2021-10-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0008_auto_20211011_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
