# Generated by Django 3.2.7 on 2021-10-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0009_alter_property_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
