# Generated by Django 3.2.7 on 2021-10-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0010_alter_property_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite_property',
            name='property',
        ),
        migrations.AddField(
            model_name='favourite_property',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to='Property.Property'),
        ),
    ]
