# Generated by Django 3.2.7 on 2021-10-14 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0011_auto_20211014_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite_property',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
