# Generated by Django 3.2.7 on 2021-10-18 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0013_auto_20211014_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteproperty',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
