# Generated by Django 3.2.7 on 2021-10-28 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0015_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_detail',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
